config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy]
  # Defines the root path route ("/")
  # root "articles#index"

  # delete "events/:id", to: "events#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :category, inclusion: %w"[ people music science politics war nature architecture ]"
  validates :era, inclusion: ["prehistory", "ancient", "post-classical", "early-modern", "late-modern"]
  validates :name, :era, :category, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
    @events = Event.where(user: current_user)
  end


  def new
    @booking = Booking.new
  end

  def create
    @event = Event.find(params[:event_id])
    @booking = Booking.new(booking_params)
    @booking.event = @event
    @booking.user = current_user
    if @booking.save
      redirect_to event_path(@event)
    else
      render 'events/show', status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to booking_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :rich)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def show
    @event = Event.find(params[:id])
    if @event.bookings.where(user: current_user).any?
      @booking = Booking.where(user: current_user).where(event: @event).last
      @booked = true
    else
      @booking = Booking.new
      @booked = false
    end
  end

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR category ILIKE :query OR era ILIKE :query"
      @events = Event.where(sql_query, query: "%#{params[:query]}%")
    else
      @events = Event.all
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to events_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Events.find(params[:id])
    @event.destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :year, :category, :price, :era, :photo, :description, :rich)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h2 class="m-3">My Bookings:</h2>
  <div class="events">
      <% @bookings.each do |booking| %>
        <div class="card-event">
          <%= cl_image_tag booking.event.photo.key, height: 300, width: 400, crop: :fill %>
              <div class="card-event-headline">
              <h3>
              <%= booking.event.name.capitalize %>
              </h3>
              <p>$ <%= booking.event.price %></p>
              </div>
              <div class="card-event-infos">
              <p><strong>Category:</strong> <%= booking.event.category %></p>
              <p><strong>Era:</strong> <%= booking.event.era %></p>
              </div>
              <div class="card-event-infos">
              <p><strong>Year:</strong> <%= booking.event.year %></p>
            </div>
              <div class="card-event-infos">
              <p id="booking-confirmation"> <strong><em> TimeScape booked! Date: <%=booking.start_date.strftime("%d.%m.%Y") %></em></strong> </p>
              </div>
            <div>
              <%= link_to "Cancel", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-primary m-2 mb-3" %>
          </div>
        </div>
      <% end %>
    </div>
  <h2 class="m-3">My Events:</h2>
  <div class="events">
      <% @events.each do |event| %>
      <%= link_to event_path(event) do%>
        <div id="card-event-id" class="card-event">
          <%= cl_image_tag event.photo.key, height: 300, width: 400, crop: :fill %>
              <div class="card-event-headline">
              <h3>
              <%= event.name.capitalize %>
              </h3>
              <p>$ <%= event.price %></p>
              </div>
              <div class="card-event-infos">
              <p><strong>Category:</strong> <%= event.category %></p>
              <p><strong>Era:</strong> <%= event.era %></p>
              </div>
              <div class="card-event-infos">
              <p><strong>Year:</strong> <%= event.year %></p>
            </div>
        </div>
      <% end %>
    <% end %>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
<div class="events">
  <% @bookings.each do |booking| %>
  <div class="card-event">
    <%= cl_image_tag booking.event.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="card-event-headline">
        <h3>
        <%= booking.event.name.capitalize %>
        </h3>
        <p>$ <%= booking.event.price %></p>
        </div>
        <div class="card-event-infos">
        <p><strong>Category:</strong> <%= booking.event.category %></p>
        <p><strong>Era:</strong> <%= booking.event.era %></p>
        </div>
        <div class="card-event-infos">
        <p><strong>Year:</strong> <%= booking.event.year %></p>
      </div>
       <h3>This event has been booked for</h3><%= booking.start_date %>
  </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="container">
  <div id="event-button">
    <%= link_to "Create a Event", new_event_path, class: "btn btn-primary" %>
  </div>
<div class="events">
  <% @events.each do |event| %>
  <%= link_to event_path(event) do%>
  <div id="card-event-id" class="card-event">
    <%= cl_image_tag event.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="card-event-headline">
          <h3>
        <%= event.name.capitalize %>
        </h3>
        <p>$ <%= event.price %></p>
        </div>
        <div class="card-event-infos">
        <p><strong>Category:</strong> <%= event.category %></p>
        <p><strong>Era:</strong> <%= event.era %></p>
        </div>
        <div class="card-event-infos">
        <p><strong>Year:</strong> <%= event.year %></p>
        </div>
  </div>
  <% end %>
  <% end %>
</div>
</div>

app/views/events/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h2 class="text-center pb-2"><strong> Your new Event</strong></h2>
          <%= simple_form_for @event do |f| %>
            <%= f.input :name, placeholder: 'Enter the name of the event' %>
            <%= f.input :year, placeholder: 'Enter which year' %>
            <%= f.input :price, placeholder: 'Enter a price' %>
            <%= f.input :description, as: :string, :input_html => { class: 'test', :cols => 2, :rows => 2 } %>
            <%= f.input :category, collection: %w"people music science politics war nature architecture" %>
            <%= f.input :era, collection: %w"prehistory ancient post-classical early-modern late-modern" %>
            <%= f.input :photo, class: "photo", as: :file %>
            <%= f.submit class: 'btn btn-primary' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="show-page">
    <div class="show-event">
      <div class="event-without-description">
        <div>
          <%= cl_image_tag @event.photo.key, height: 300, width: 400, crop: :fill %>
        </div>
        <div class="headline-keyinfo">
          <div class="show-event-headline">
            <h3><%= @event.name.capitalize %></h3>
            <p>$<%= @event.price %></p>
          </div>
          <div class="show-event-infos">
            <p><strong>Category:</strong> <%= @event.category %></p>
            <p><strong>Era:</strong> <%= @event.era %></p>
            <p><strong>Year:</strong> <%= @event.year %></p>
            <p><strong>Description:</strong> <%= @event.description %></p>
          </div>

        </div>
      </div>
    </div>


   <div class="booking-request">
       <% if @booked %>
       <div id="booked">
        <p ><strong>TimeScape booked! </strong> </p>
        <p>You will travel back in time to this event on <strong><%=  @booking.start_date.strftime("%d.%m.%Y") %></strong></p>
        </div>
       <% else %>
        <h2 class="form-h2">Create a new booking:</h2>
        <%= simple_form_for [@event, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
           <%= f.input :rich  %>
          <%= f.button :submit, class: "btn btn-back" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelBackInTime</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Kaushan+Script&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%# <%= image_tag '/images/logo.png'%>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/All_Gizah_Pyramids.jpg/1920px-All_Gizah_Pyramids.jpg">
        Travel back in Time
  </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
              <div class = "container d-flex align-items-inline justify-content-center">
              <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get" >
                <div class="search-form-control form-group">
                  <input class="form-control string required" type="text" name="search[query]" id="search_query" />
                  <button name="button" type="submit" class="btn btn-flat">
                    <i class="fas fa-search"></i> Search
                  </button>
                </div>
              </form>
              </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Messages</a>
            </li>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
              </div>
            </li>
            <!--li class="nav-item"-->
            <!--/li-->
        </ul>
      </div>
    </div>
  </div>

</div>


<div>

</div>


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <p><em> <i class="fa-solid fa-clock-rotate-left"></i> Experience History like never before <i class="fa-solid fa-clock-rotate-left"></i> </em></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to events_path do  %>
      <%= image_tag 'TimeSpace.png', class: 'navbar-image' %>
      <% end %>
      <!-- <img src="images/TimeSpace.png"> -->
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class = "container d-flex align-items-inline justify-content-center">
      <%= form_with url: events_path, method: :get, class: "d-flex" do %>
        <div class="search-form-control form-group">
          <%= text_field_tag :query, params[:query], class: "form-control string required", placeholder: "Find your time!" %>
              <%= button_tag "Now!", class: "btn btn-alert" do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <%= link_to "Home", events_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://media.tenor.com/wwAEuo91OgsAAAAd/tammy-and-the-trex-dinosaur.gif" />
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <% if current_user %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class:"dropdown-item" %>
            <%= link_to "Dahsboard", bookings_path, class:"dropdown-item" %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class:"dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>